// Generated by tools/generate-rating-assets.js. Do not edit.
#pragma once
#include <string>
namespace ssc {
inline std::string ratingAssetPath(const std::string& country, const std::string& system,
                                   const std::string& rating) {
    static const struct { const char *country, *system, *rating, *path; } assets[] = {
        { "DE", "FSK", "0", "/ratings/v1/de_fsk_0.7f540a6545cb.png" },
        { "DE", "FSK", "6", "/ratings/v1/de_fsk_6.3fbefdcc120c.png" },
        { "DE", "FSK", "12", "/ratings/v1/de_fsk_12.73a0f1640cf6.png" },
        { "DE", "FSK", "16", "/ratings/v1/de_fsk_16.bed0656b31fb.png" },
        { "DE", "FSK", "18", "/ratings/v1/de_fsk_18.685f05c6a775.png" },
        { "US", "MPA", "G", "/ratings/v1/us_mpa_g.b9b221b45c3a.png" },
        { "US", "MPA", "PG", "/ratings/v1/us_mpa_pg.620c2b54fed4.png" },
        { "US", "MPA", "PG-13", "/ratings/v1/us_mpa_pg_13.832960b44490.png" },
        { "US", "MPA", "R", "/ratings/v1/us_mpa_r.7cc5d6f5a230.png" },
        { "US", "MPA", "NC-17", "/ratings/v1/us_mpa_nc_17.0af5fe4e9765.png" },
        { "US", "TV Parental Guidelines", "TV-Y", "/ratings/v1/us_tv_parental_guidelines_tv_y.70e33b3f84f5.png" },
        { "US", "TV Parental Guidelines", "TV-Y7", "/ratings/v1/us_tv_parental_guidelines_tv_y7.33b88a7bf900.png" },
        { "US", "TV Parental Guidelines", "TV-Y7-FV", "/ratings/v1/us_tv_parental_guidelines_tv_y7_fv.d7ce8a445270.png" },
        { "US", "TV Parental Guidelines", "TV-G", "/ratings/v1/us_tv_parental_guidelines_tv_g.7082a1f2fdba.png" },
        { "US", "TV Parental Guidelines", "TV-PG", "/ratings/v1/us_tv_parental_guidelines_tv_pg.bde60676d33a.png" },
        { "US", "TV Parental Guidelines", "TV-14", "/ratings/v1/us_tv_parental_guidelines_tv_14.33894cfc7b3e.png" },
        { "US", "TV Parental Guidelines", "TV-MA", "/ratings/v1/us_tv_parental_guidelines_tv_ma.57b822c9dc9b.png" }
    };
    for (const auto& asset : assets)
        if (country == asset.country && system == asset.system && rating == asset.rating) return asset.path;
    return {};
}
} // namespace ssc
